### ISSUE TITLE
master & develop branches question

### ISSUE THREAD

**Issue by trilopin** [OpenSRS/osrs-toolkit-php#20]
At first, project appeared unmantained. 
Later I saw develop branch had recent changes and it was "531 commits ahead of master".

Are there any plan to release? 
Is correct to PR master branch?

Regards

**Comment by arleslie** [comment]
Would be nice to know about the status of this. 

@colincode you seem active on this project, and this is your branch in mention. Can you provide any insight?

**Comment by oucil** [comment]
+1  is this project in active development? The mail API on the master branch seems VERY out of date.

**Comment by colincode** [comment]
We have been doing some updates to the domain side of things.  Which you guys have seen in the develop branch.  It should be backwards compatible with the previous release, and has a few new features.  I haven't' had any request for MailAPI changes yet so it's status quo. 

Not sure on a release date yet, but it is in the works.

**Comment by oucil** [comment]
@colincode How stable is the MailAPI stuff though, this is a dev branch after all?  The problem is that a number of the most important classes (i.e. CreateDomain, CreateAlias, etc.) don't even exist in the master branch's mail classes.

What's the reason for being 500+ commits beyond the master and not pushing to master?  The last actual release or tag was just about 3 years ago.

**Comment by trilopin** [comment]
@colincode would be php7 compatible?

**Comment by oucil** [comment]
@colincode Any chance you can address my last questions about the Mail API stability from two weeks ago???  It looks like half the features of your mail API are missing from the master branch, including really important ones like CreateDomain, and CreateMailbox.... can I rely on these being stable in this Dev branch?  I need access to these hooks in production because we're prepping for a major push in this area to grow our clientelle, but if they're not stable, which only you can tell me, how am I supposed to base my companies growth on your API?  Lastly, why is it taking two weeks to get back to people on your branch, considering the size of OpenSRS, and the importance of an API?  I'm not trying to be confrontational here, really, and I understand dev timelines and unknowns, but there are a LOT of unknowns here, and I'm not the only one looking for answers to these questions.  Please do us a favour and shed some light on what we can and can't rely on.  Thank you.

**Comment by colincode** [comment]
@oucil We have no pending feature updates to the mail api in develop that are not in master.  Most of the changes are refactoring.  

If you are concerned about stability and have used it before I would stick to the master branch for now.  

If you are using it for a new project, then by all means use the develop branch.  It has composer support, and cleaner (IMO) OO way of handling requests.

I totally understand your frustrations.  I'm trying to get some weekly scheduled time to work on this.  And hopefully improve my response times & general activity level on this project.

**Comment by colincode** [comment]
@trilopin We did a round of php7 updates for the develop branch but like your pull request suggests, there may be some missing.

**Comment by oucil** [comment]
@colincode This is a new development we're working on, so there's some flexibility but it's good to hear that you don't have any immediate plans for changing it, it looks like it has the hooks we need for now.  If we run into any problems or needs that I can help solve with a PR, I'm assuming your open to community support?

Thanks for getting back, if we do have more urgent questions in the future (promise not to abuse) is there a better way to contact you for help?  Through OpenSRS Support, private message, other?  Thanks again.

**Comment by colincode** [comment]
@oucil Yes totally welcome to community support.  

For urgent issues, OpenSRS Support is your best bet.  They should be able to direct your call to the most appropriate party.  Which may not always be me.
